apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-mysql
  namespace: microforge-dev-ns
  labels:
    app: login-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-mysql
  template:
    metadata:
      labels:
        app: login-mysql
    spec:
      containers:
        - name: login-mysql
          image: manojmdocker14/microforge-users-mysql:v1.0.0
          ports:
            - containerPort: 3306
          startupProbe:
            exec:
              command:
                - bash
                - "-c"
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}" 
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: login-mysql-config
            - secretRef:
                name: login-mysql-secret
    